### ISSUE TITLE
建议提供一套标准化的输出包

### ISSUE THREAD

**Issue by DVKunion** [chaitin/veinmind-common-go#20]
大前提：所有的插件都要输出展示
小前提：输出展示的格式无非json/html/pdf/sarif， 且目前数据都通过report的方式上报上来
结论：我们需要一个标准化的输出包，来节约在编写插件时输出展示方面重复浪费掉的时间

**Comment by d1nfinite** [comment]
如果数据都是 `json`，有办法较好的展示成 `html`/`pdf` 吗

**Comment by DVKunion** [comment]
需要调研一下，主要的问题在于需要定义好固定字段和高可扩展字段的展示

**Comment by d1nfinite** [comment]
这个不着急，可以先搞定 IAC 相关的事情
